#! /usr/bin/env python

import sferes;

def build(bld):
    cxxflags_kdtree = \
        bld.get_env()['CXXFLAGS']\
        + ['-I.'] \
        + ['-DLIBSSRCKDTREE_HAVE_BOOST'] \
        + ['-std=c++0x'] \
        + ['-m32']

#    lz = bld.new_task_gen('cxx', 'staticlib')
#    lz.source = 'fastlz.cpp'
#    lz.target = 'lz'

#    bld.get_env()['LIB_BZIP2'] = 'bzip2'
#    bld.get_env()['CPPPATH_BZIP2'] = 'bzlib2/include/'
#    bld.get_env()['LIBPATH_BZIP2'] = 'bzlib2/lib/'

#bz = bld.new_task_gen('cxx', 'staticlib')
    #bz.source = 'bzlib2/bzlib.cpp'
    #bz.target = 'bz'

    sferes.create_variants(bld,
                           source='StagHuntExp3.cpp',
                           uselib_local = 'sferes2 fastsim_multi',
#                           uselib = 'EIGEN2 TBB',
                           uselib = 'EIGEN2 SDL FF BOOST_GRAPH TBB',
                           target = 'StagHuntExp3',
                           json = 'StagHuntExp3.json',
                           variants = [
                           							'PARALLEL MLP ELITIST CONTROL2 PREYS18 MAP800 POS_CLOSE HIGH_STAMINA SSTAG500 STEPS20000 TRIALS5',

                           							'PARALLEL MLP ELITIST CONTROL1 PREYS8 MAP800 HIGH_STAMINA BSTAG1000 STEPS20000 TRIALS5',
                           							'PARALLEL MLP ELITIST CONTROL1 PREYS18 MAP800 HIGH_STAMINA BSTAG1000 STEPS20000 TRIALS5',
                           							'PARALLEL MLP ELITIST CONTROL1 PREYS36 MAP800 HIGH_STAMINA BSTAG1000 STEPS20000 TRIALS5',
                           							
                           							'PARALLEL MLP ELITIST CONTROL2 PREYS8 MAP800 HIGH_STAMINA SSTAG500 STEPS20000 TRIALS5',
                           							'PARALLEL MLP ELITIST CONTROL2 PREYS18 MAP800 HIGH_STAMINA SSTAG500 STEPS20000 TRIALS5',
                           							'PARALLEL MLP ELITIST CONTROL2 PREYS36 MAP800 HIGH_STAMINA SSTAG500 STEPS20000 TRIALS5',

                           							'PARALLEL MLP ELITIST CONTROL4 PREYS8 MAP800 HIGH_STAMINA SSTAG500 STEPS20000 TRIALS5',
                           							'PARALLEL MLP ELITIST CONTROL4 PREYS18 MAP800 HIGH_STAMINA SSTAG500 STEPS20000 TRIALS5',
                           							'PARALLEL MLP ELITIST CONTROL4 PREYS36 MAP800 HIGH_STAMINA SSTAG500 STEPS20000 TRIALS5',
                           							
                           							'PARALLEL MLP ELITIST CONTROL2 PREYS8 MAP800 HIGH_STAMINA SSTAG500 STEPS20000 OPPONENTS20 TRIALS1',
                           							'PARALLEL MLP ELITIST CONTROL2 PREYS8 MAP800 HIGH_STAMINA SSTAG500 STEPS20000 OPPONENTS10 TRIALS2',
                           							'PARALLEL MLP ELITIST CONTROL2 PREYS8 MAP800 HIGH_STAMINA SSTAG500 STEPS20000 OPPONENTS10 TRIALS1',
                           							'PARALLEL MLP ELITIST CONTROL2 PREYS8 MAP800 HIGH_STAMINA SSTAG500 STEPS20000 OPPONENTS5 TRIALS2',
                           							'PARALLEL MLP ELITIST CONTROL2 PREYS8 MAP800 HIGH_STAMINA SSTAG500 STEPS20000 OPPONENTS5 TRIALS1',
                           							'PARALLEL MLP ELITIST CONTROL2 PREYS8 MAP800 HIGH_STAMINA SSTAG500 STEPS20000 OPPONENTS2 TRIALS10',
                           							'PARALLEL MLP ELITIST CONTROL2 PREYS8 MAP800 HIGH_STAMINA SSTAG500 STEPS20000 OPPONENTS1 TRIALS20',
                           							
                           							'PARALLEL MLP ELITIST SETTING13 PREYS8 MOVING_PREYS MAP400 HIGH_STAMINA STEPS20000 TRIALS5',
                                       ])
                                       
#def build(bld):
#    obj = bld.new_task_gen('cxx', 'program')
#    obj.source = 'StagHuntExp1.cpp'
#    obj.includes = '. ../../'
#    obj.uselib_local = 'sferes2'
#    obj.uselib = ''
#    obj.target = 'StagHuntExp1'
#    obj.uselib_local = 'sferes2'
