#! /usr/bin/env python

import sferes;

def build(bld):
    cxxflags_kdtree = \
        bld.get_env()['CXXFLAGS']\
        + ['-I.'] \
        + ['-DLIBSSRCKDTREE_HAVE_BOOST'] \
        + ['-std=c++0x'] \
        + ['-m32']

#    lz = bld.new_task_gen('cxx', 'staticlib')
#    lz.source = 'fastlz.cpp'
#    lz.target = 'lz'

#    bld.get_env()['LIB_BZIP2'] = 'bzip2'
#    bld.get_env()['CPPPATH_BZIP2'] = 'bzlib2/include/'
#    bld.get_env()['LIBPATH_BZIP2'] = 'bzlib2/lib/'

#bz = bld.new_task_gen('cxx', 'staticlib')
    #bz.source = 'bzlib2/bzlib.cpp'
    #bz.target = 'bz'

    sferes.create_variants(bld,
                           source='StagHuntExp3.cpp',
                           uselib_local = 'sferes2 fastsim_multi',
#                           uselib = 'EIGEN2 TBB',
                           uselib = 'EIGEN2 SDL FF BOOST_GRAPH TBB',
                           target = 'StagHuntExp3',
                           json = 'StagHuntExp3.json',
                           variants = [
                    #                     'PARALLEL MLP FITPROP CONTROL1 PREYS18 NEW_CAMERA MAP800 HIGH_STAMINA BSTAG500 STEPS20000 TRIALS5',
                    #                     'PARALLEL MLP MLP_PERSO FITPROP CONTROL1 ALTRUISM PREYS18 NEW_CAMERA MAP800 HIGH_STAMINA BSTAG500 STEPS20000 TRIALS5',
                    #                     'PARALLEL MLP MLP_PERSO FITPROP CONTROL1 PREYS18 NEW_CAMERA MAP800 HIGH_STAMINA BSTAG500 BSTAG_SOLO50 STEPS20000 TRIALS5',
																				# 'PARALLEL MLP MLP_PERSO FITPROP SETTING13 PREYS18 NEW_CAMERA MAP800 HIGH_STAMINA BSTAG500 BSTAG_SOLO50 STEPS20000 TRIALS5',
                                        # 'PARALLEL MLP MLP_PERSO FITPROP CONTROL1 ALTRUISM PREYS18 NEW_CAMERA MAP800 HIGH_STAMINA BSTAG500 BSTAG_SOLO50 STEPS20000 TRIALS5',
                                        # 'PARALLEL MLP MLP_PERSO FITPROP SETTING13 PREYS2 NEW_CAMERA MAP800 HIGH_STAMINA BSTAG500 STEPS20000 TRIALS5',
                                        # 'PARALLEL MLP MLP_PERSO FITPROP CONTROL1 PREYS2 NEW_CAMERA MAP800 HIGH_STAMINA BSTAG500 BSTAG_SOLO50 STEPS20000 TRIALS5',
                                        # 'PARALLEL MLP MLP_PERSO FITPROP CONTROL1 PREYS18 NEW_CAMERA MAP800 HIGH_STAMINA BSTAG500 BSTAG_SOLO100 STEPS20000 TRIALS5',
                                        'PARALLEL MLP MLP_PERSO FITPROP SETTING14 PREYS18 NEW_CAMERA MAP800 HIGH_STAMINA SSTAG500 STEPS20000 TRIALS5',
                                      ])
                                       
#def build(bld):
#    obj.source = 'StagHuntExp1.cpp'
#    obj.includes = '. ../../'
#    obj.uselib_local = 'sferes2'
#    obj.uselib = ''
#    obj.target = 'StagHuntExp1'
#    obj.uselib_local = 'sferes2'
