#! /usr/bin/env python

import sferes;

def build(bld):
		cxxflags_kdtree = \
				bld.get_env()['CXXFLAGS']\
				+ ['-I.'] \
				+ ['-DLIBSSRCKDTREE_HAVE_BOOST'] \
				+ ['-std=c++0x'] \
				+ ['-m32']

#    lz = bld.new_task_gen('cxx', 'staticlib')
#    lz.source = 'fastlz.cpp'
#    lz.target = 'lz'

#    bld.get_env()['LIB_BZIP2'] = 'bzip2'
#    bld.get_env()['CPPPATH_BZIP2'] = 'bzlib2/include/'
#    bld.get_env()['LIBPATH_BZIP2'] = 'bzlib2/lib/'

#bz = bld.new_task_gen('cxx', 'staticlib')
		#bz.source = 'bzlib2/bzlib.cpp'
		#bz.target = 'bz'

		sferes.create_variants(bld,
													 source='StagHunt.cpp',
													 uselib_local = 'sferes2 fastsim_multi',
#                           uselib = 'EIGEN2 TBB',
													 uselib = 'EIGEN2 SDL FF BOOST_GRAPH TBB',
													 target = 'StagHunt',
#                           json = 'StagHuntExp3.json',
													 variants = [
													 							# 'SETTING14 COEVO SSTAG250 GBEARD',
													 							# 'SETTING14 COEVO SSTAG250 GBEARD FIXED_CHOICE',
													 							# 'SETTING14 COEVO SSTAG250 GBEARD NETWORK_DOUBINPUTS',
													 							# 'SETTING14 SSTAG50 GBEARD',
													 							# 'SETTING14 SSTAG50 GBEARD FIXED_CHOICE',
													 							# 'SETTING14 SSTAG50 GBEARD NETWORK_DOUBINPUTS',
													 							# 'SETTING14 POP100 SSTAG50',
													 							# 'SETTING14 POP200 SSTAG50',
													 							# 'SETTING14 POP100 SSTAG250',
													 							# 'SETTING14 POP200 SSTAG250',
													 							# 'SETTING14 SSTAG250',
													 							# 'SETTING14 SSTAG250 PARTNER_SELECT GEN_DIV SEVERAL_LISTS',
													 							# 'SETTING14 SSTAG250 PARTNER_SELECT GEN_DIV',
													 							# 'SETTING14 SSTAG250 PARTNER_SELECT GBEARD SEVERAL_LISTS',
													 							# 'SETTING14 SSTAG250 PARTNER_SELECT GBEARD',
													 							# 'SETTING14 SSTAG250 PARTNER_SELECT GBEARD FIXED_CHOICE SEVERAL_LISTS',
													 							# 'SETTING14 SSTAG250 PARTNER_SELECT GBEARD FIXED_CHOICE',
													 							# 'SETTING14 SSTAG250 PARTNER_SELECT GBEARD NETWORK_DOUBINPUTS SEVERAL_LISTS',
													 							# 'SETTING14 SSTAG250 PARTNER_SELECT GBEARD NETWORK_DOUBINPUTS',
													 							# 'SETTING14 SSTAG50 DIVERSITY',

													 							# 'SETTING14 SSTAG50 DIVERSITY NEVAL_ALL',
													 							# 'SETTING14 FITPROP STD2 SSTAG50',
													 							# 'SETTING14 STD2 SSTAG50 DIVERSITY',
													 							# 'SETTING14 STD2 SSTAG250 DIVERSITY',
													 							# 'SETTING14 SSTAG250 DIVERSITY',

													 							# 'SETTING14 FITPROP POP40 STD2 SSTAG250',
													 							# 'SETTING14 FITPROP POP40 POLYNOMIAL SSTAG250',
													 							# 'SETTING14 FITPROP STD3 SSTAG250',
													 							# 'SETTING14 FITPROP STD4 SSTAG250',
													 							# 'SETTING14 FITPROP POLYNOMIAL SSTAG250',
													 							# 'SETTING14 FITPROP UNIFORM_MUTATION SSTAG250',
													 							# 'SETTING14 FITPROP STEP_SIZE SSTAG250',
													 							# 'SETTING14 FITPROP STEP_SIZE MUT_APP_RATE RATE5 SSTAG250',
													 							# 'SETTING14 FITPROP UNIFORM_MUTATION MUT_APP_RATE RATE5 SSTAG250',
													 							# 'SETTING14 FITPROP UNIFORM_MUTATION MUT_APP_RATE RATE25 SSTAG250',
													 							# 'SETTING14 SSTAG250',

													 							# ---- POP20 EXPERIMENTS ----
													 							'SETTING14 FITPROP STD2 SSTAG250',
													 							'SETTING14 SSTAG250',

													 							# ---- POP40 EXPERIMENTS ----
													 							'SETTING14 FITPROP POP40 STD2 SSTAG250',
													 							'SETTING14 POP40 MU20 LAMBDA20 SSTAG250',

													 							# ---- POP100 EXPERIMENTS ----
													 							'SETTING14 FITPROP POP100 STD2 SSTAG250',
													 							'SETTING14 POP100 MU50 LAMBDA50 SSTAG250',

													 							# ---- COEVO ----
													 							'SETTING14 COEVO SSTAG250',

													 							# ---- COEVO3 ----
													 							'SETTING14 PAIRING NICHE3 MU7 LAMBDA7 AGAINST_ALL_NICHES SSTAG250',

													 							# 'SETTING14 TUPLES TUPLE_SWAP SSTAG250',
													 							# 'SETTING14 TUPLES TUPLE_SWAP STD2 SSTAG250',
													 							# 'SETTING14 NEVAL_PARENTS TUPLES TUPLE_SWAP SSTAG250',
													 							# 'SETTING14 ONE_PLUS_ONE_REPLACEMENT MU2 LAMBDA2 POP_INIT20 SSTAG250',
													 							# 'SETTING14 ONE_PLUS_ONE_REPLACEMENT SEPARATE_PARENTS MU2 LAMBDA2 POP_INIT20 SSTAG250',
													 							# 'SETTING14 ONE_PLUS_ONE_REPLACEMENT SEPARATE_PARENTS MU2 LAMBDA2 POP_INIT20 STD2 SSTAG250',
													 							# 'SETTING14 ONE_PLUS_ONE_REPLACEMENT NEVAL_PARENTS MU2 LAMBDA2 POP_INIT20 SSTAG250',

													 							# 'SETTING14 COEVO MU1 LAMBDA1 POP_INIT20 SSTAG250',
													 							# 'SETTING14 NO_STEP_SIZE SSTAG250',

													 							# 'SETTING14 PAIRING NICHE2 MU1 LAMBDA1 POP_INIT20 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE4 MU1 LAMBDA1 POP_INIT20 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE4 MU2 LAMBDA2 POP_INIT20 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE10 MU1 LAMBDA1 POP_INIT20 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE10 MU1 LAMBDA1 AGAINST_ALL_NICHES POP_INIT20 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE4 MU1 LAMBDA1 EVOL_PAIRING POP_INIT20 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE4 MU2 LAMBDA2 EVOL_PAIRING POP_INIT20 SSTAG250',

													 							# 'SETTING14 COEVO MU8 LAMBDA8 SSTAG250',
													 							# 'SETTING14 COEVO MU8 LAMBDA8 POP_INIT20 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE4 MU2 LAMBDA2 PRUNING REPLACE_WORST EVAL_PRUNING1000 POP_INIT20 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE4 MU2 LAMBDA2 PRUNING REPLACE_WORST POP_INIT20 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE4 MU1 LAMBDA1 POP_INIT20 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE4 MU2 LAMBDA2 POP_INIT20 SSTAG250',
													 							# 'SETTING14 COEVO MU8 LAMBDA8 POP_INIT24 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE4 MU2 LAMBDA2 PRUNING REPLACE_WORST POP_INIT24 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE4 MU4 LAMBDA4 POP_INIT24 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE4 MU4 LAMBDA4 PRUNING REPLACE_WORST POP_INIT24 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE4 MU4 LAMBDA4 PRUNING REPLACE_WORST EVAL_PRUNING200 POP_INIT24 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE4 MU4 LAMBDA4 PRUNING REPLACE_WORST EVAL_PRUNING100 POP_INIT24 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE8 MU2 LAMBDA2 POP_INIT24 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE8 MU2 LAMBDA2 PRUNING REPLACE_WORST POP_INIT24 SSTAG250',

													 							# 'SETTING14 PAIRING NICHE2 MU1 LAMBDA1 POP_INIT20 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE4 MU1 LAMBDA1 AGAINST_ALL_NICHES POP_INIT20 SSTAG250',
													 							# 'SETTING14 PAIRING NICHE4 MU2 LAMBDA2 AGAINST_ALL_NICHES POP_INIT20 SSTAG250',

													 							# 'SETTING14 ONE_PLUS_ONE_REPLACEMENT MU2 LAMBDA2 SSTAG250',
													 							# 'SETTING14 ONE_PLUS_ONE_REPLACEMENT MU2 LAMBDA2 STD2 SSTAG250',
													 							# 'SETTING14 ONE_PLUS_ONE_REPLACEMENT MU2 LAMBDA2 POP_INIT20 SSTAG250',
													 							# 'SETTING14 ONE_PLUS_ONE_REPLACEMENT MU2 LAMBDA2 RANDOM_MUTANT SSTAG250',

													 							# 'SETTING14 ONE_PLUS_ONE_REPLACEMENT SSTAG250',
													 							# 'SETTING14 ONE_PLUS_ONE_REPLACEMENT STD2 SSTAG250',

													 							# 'SETTING14 ONE_PLUS_ONE_REPLACEMENT RANDOM_MUTANT SSTAG250',
													 							# 'SETTING14 ONE_PLUS_ONE_REPLACEMENT DIVERSITY RESTART SSTAG250',

													 							# 'SETTING14 FITNESS_SHARING SSTAG250',
																			])

																			 
#def build(bld):
#    obj.source = 'StagHuntExp1.cpp'
#    obj.includes = '. ../../'
#    obj.uselib_local = 'sferes2'
#    obj.uselib = ''
#    obj.target = 'StagHuntExp1'
#    obj.uselib_local = 'sferes2'
