#! /usr/bin/env python

import sferes;

def build(bld):
		cxxflags_kdtree = \
				bld.get_env()['CXXFLAGS']\
				+ ['-I.'] \
				+ ['-DLIBSSRCKDTREE_HAVE_BOOST'] \
				+ ['-std=c++0x'] \
				+ ['-m32']

#    lz = bld.new_task_gen('cxx', 'staticlib')
#    lz.source = 'fastlz.cpp'
#    lz.target = 'lz'

#    bld.get_env()['LIB_BZIP2'] = 'bzip2'
#    bld.get_env()['CPPPATH_BZIP2'] = 'bzlib2/include/'
#    bld.get_env()['LIBPATH_BZIP2'] = 'bzlib2/lib/'

#bz = bld.new_task_gen('cxx', 'staticlib')
		#bz.source = 'bzlib2/bzlib.cpp'
		#bz.target = 'bz'

		sferes.create_variants(bld,
													 source='StagHunt.cpp',
													 uselib_local = 'sferes2 fastsim_multi',
#                           uselib = 'EIGEN2 TBB',
													 uselib = 'EIGEN2 SDL FF BOOST_GRAPH TBB',
													 target = 'StagHunt',
#                           json = 'StagHuntExp3.json',
													 variants = [
													 							# 'NO_SHARING',
													 							# 'NO_SHARING FOOD_MAX',
													 							# 'NO_REPUTATION',
													 							# 'NO_REPUTATION FOOD_MAX',

													 							# 'FIXED_REPUTATION UNKNOWN_MEAN',
													 							# 'FIXED_REPUTATION UNKNOWN_BEST',
													 							
													 							# 'EXP',
													 							'EXP FOOD_MAX',
													 							# 'EXP INTERACTION_MEMORY',
													 							# 'EXP INTERACTION_MEMORY FOOD_MAX',
																			])

																			 
#def build(bld):
#    obj.source = 'StagHuntExp1.cpp'
#    obj.includes = '. ../../'
#    obj.uselib_local = 'sferes2'
#    obj.uselib = ''
#    obj.target = 'StagHuntExp1'
#    obj.uselib_local = 'sferes2'
