#! /usr/bin/env python

import sferes;

def build(bld):
    cxxflags_kdtree = \
        bld.get_env()['CXXFLAGS']\
        + ['-I.'] \
        + ['-DLIBSSRCKDTREE_HAVE_BOOST'] \
        + ['-std=c++0x'] \
        + ['-m32']

#    lz = bld.new_task_gen('cxx', 'staticlib')
#    lz.source = 'fastlz.cpp'
#    lz.target = 'lz'

#    bld.get_env()['LIB_BZIP2'] = 'bzip2'
#    bld.get_env()['CPPPATH_BZIP2'] = 'bzlib2/include/'
#    bld.get_env()['LIBPATH_BZIP2'] = 'bzlib2/lib/'

#bz = bld.new_task_gen('cxx', 'staticlib')
    #bz.source = 'bzlib2/bzlib.cpp'
    #bz.target = 'bz'

    sferes.create_variants(bld,
                           source='StagHunt.cpp',
                           uselib_local = 'sferes2 fastsim_multi',
#                           uselib = 'EIGEN2 TBB',
                           uselib = 'EIGEN2 SDL FF BOOST_GRAPH TBB',
                           target = 'StagHunt',
#                           json = 'StagHuntExp3.json',
                           variants = [
                                        # 'COEVO WAYPOINTS7 POS_CLOSE',
                                        # 'COEVO WAYPOINTS12 POS_CLOSE',
                                        'COEVO WAYPOINTS18 POS_CLOSE',
                                        'COEVO WAYPOINTS18 POS_CLOSE NO_COORD',
                                        # 'WAYPOINTS7 ID_LEADER POS_CLOSE',
                                        # 'WAYPOINTS12 ID_LEADER POS_CLOSE',
                                        # 'WAYPOINTS18 ID_LEADER POS_CLOSE',
                                      ])

                                       
#def build(bld):
#    obj.source = 'StagHuntExp1.cpp'
#    obj.includes = '. ../../'
#    obj.uselib_local = 'sferes2'
#    obj.uselib = ''
#    obj.target = 'StagHuntExp1'
#    obj.uselib_local = 'sferes2'
