#! /usr/bin/env python

import sferes;

def build(bld):
    cxxflags_kdtree = \
        bld.get_env()['CXXFLAGS']\
        + ['-I.'] \
        + ['-DLIBSSRCKDTREE_HAVE_BOOST'] \
        + ['-std=c++0x'] \
        + ['-m32']

#    lz = bld.new_task_gen('cxx', 'staticlib')
#    lz.source = 'fastlz.cpp'
#    lz.target = 'lz'

#    bld.get_env()['LIB_BZIP2'] = 'bzip2'
#    bld.get_env()['CPPPATH_BZIP2'] = 'bzlib2/include/'
#    bld.get_env()['LIBPATH_BZIP2'] = 'bzlib2/lib/'

#bz = bld.new_task_gen('cxx', 'staticlib')
    #bz.source = 'bzlib2/bzlib.cpp'
    #bz.target = 'bz'

    sferes.create_variants(bld,
                           source='StagHunt.cpp',
                           uselib_local = 'sferes2 fastsim_multi',
#                           uselib = 'EIGEN2 TBB',
                           uselib = 'EIGEN2 SDL FF BOOST_GRAPH TBB',
                           target = 'StagHunt',
#                           json = 'StagHuntExp3.json',
                           variants = [
                                        # 'CONTROL1 COEVO BSTAG250 POS_CLOSE',
                                        # 'CONTROL1 BSTAG250 POS_CLOSE',
                                        # 'CONTROL1 BSTAG250 POS_CLOSE ALTRUISM',
                                        'CONTROL2 COEVO SSTAG250 POS_CLOSE',
                                        'CONTROL2 COEVO SSTAG125 POS_CLOSE',
                                        'CONTROL3 COEVO BSTAG250 SSTAG125 POS_CLOSE',
                                        'CONTROL3 COEVO BSTAG500 SSTAG250 POS_CLOSE',

																				'SETTING15 BSTAG250 POS_CLOSE',
                                        'SETTING15 DOUBLE_NN BSTAG250 POS_CLOSE',
                                        'SETTING15 DOUBLE_NN DECISION_THRESHOLD BSTAG250 POS_CLOSE',
                                        'SETTING15 DOUBLE_NN DIFF_FIT FITFOLLOW BSTAG250 POS_CLOSE'
                                      ])

                                       
#def build(bld):
#    obj.source = 'StagHuntExp1.cpp'
#    obj.includes = '. ../../'
#    obj.uselib_local = 'sferes2'
#    obj.uselib = ''
#    obj.target = 'StagHuntExp1'
#    obj.uselib_local = 'sferes2'
