#! /usr/bin/env python

import sferes;

def build(bld):
		cxxflags_kdtree = \
				bld.get_env()['CXXFLAGS']\
				+ ['-I.'] \
				+ ['-DLIBSSRCKDTREE_HAVE_BOOST'] \
				+ ['-std=c++0x'] \
				+ ['-m32']

#    lz = bld.new_task_gen('cxx', 'staticlib')
#    lz.source = 'fastlz.cpp'
#    lz.target = 'lz'

#    bld.get_env()['LIB_BZIP2'] = 'bzip2'
#    bld.get_env()['CPPPATH_BZIP2'] = 'bzlib2/include/'
#    bld.get_env()['LIBPATH_BZIP2'] = 'bzlib2/lib/'

#bz = bld.new_task_gen('cxx', 'staticlib')
		#bz.source = 'bzlib2/bzlib.cpp'
		#bz.target = 'bz'

		sferes.create_variants(bld,
													 source='StagHunt.cpp',
													 uselib_local = 'sferes2 fastsim_multi',
#                           uselib = 'EIGEN2 TBB',
													 uselib = 'EIGEN2 SDL FF BOOST_GRAPH TBB',
													 target = 'StagHunt',
#                           json = 'StagHuntExp3.json',
													 variants = [
													 							'CONTROL1 INFINITE RATE1 BSTAG_SOLO500',
													 							'CONTROL1 INFINITE RATE100 BSTAG_SOLO500',
													 							'CONTROL1 INFINITE RATE150 BSTAG_SOLO500',
													 							'CONTROL1 INFINITE RATE300 BSTAG_SOLO500',
													 							# 'CONTROL1 INFINITE RATE150 BSTAG_SOLO500 NO_MUT_APP',
													 							# 'CONTROL1 INFINITE RATE150 BSTAG_SOLO500 NO_FREQ_DEP',

													 							'CONTROL1 ELITIST ONEPLUSONE RATE1 BSTAG_SOLO500',
													 							'CONTROL1 ELITIST ONEPLUSONE RATE100 BSTAG_SOLO500',
													 							'CONTROL1 ELITIST ONEPLUSONE RATE150 BSTAG_SOLO500',
													 							'CONTROL1 ELITIST ONEPLUSONE RATE300 BSTAG_SOLO500',

													 							'CONTROL1 ELITIST ONEPLUSONE RATE1 NEVAL_PARENTS BSTAG_SOLO500',
													 							'CONTROL1 ELITIST ONEPLUSONE RATE100 NEVAL_PARENTS BSTAG_SOLO500',
													 							'CONTROL1 ELITIST ONEPLUSONE RATE150 NEVAL_PARENTS BSTAG_SOLO500',
													 							'CONTROL1 ELITIST ONEPLUSONE RATE300 NEVAL_PARENTS BSTAG_SOLO500',

													 							# 'CONTROL1 FITPROP FINITE RATE01 BIG_MUTATION_RATE BSTAG_SOLO500 POP_INIT50 POP1000 TRIALS25',
													 							# 'CONTROL1 FITPROP FINITE RATE01 BIG_MUTATION_RATE BSTAG_SOLO500 POP_INIT50 POP1000 TRIALS15',
													 							# 'CONTROL1 FITPROP FINITE RATE005 BIG_MUTATION_RATE BSTAG_SOLO500 POP_INIT50 POP1000 TRIALS25',
													 							# 'CONTROL1 FITPROP FINITE RATE005 BIG_MUTATION_RATE BSTAG_SOLO500 POP_INIT50 POP1000 TRIALS15',

													 							# 'CONTROL1 FITPROP FINITE RATE01 BIG_MUTATION_RATE BSTAG_SOLO500 POP_INIT10 POP1000 MULTIPLE_OFFSPRINGS OFF1',
													 							# 'CONTROL1 FITPROP FINITE RATE005 BIG_MUTATION_RATE BSTAG_SOLO500 POP_INIT50 POP1000 MULTIPLE_OFFSPRINGS OFF1',
													 							# 'CONTROL1 FITPROP FINITE RATE01 BIG_MUTATION_RATE BSTAG_SOLO500 POP_INIT50 POP1000 MULTIPLE_OFFSPRINGS OFF5',
													 							# 'CONTROL1 FITPROP FINITE RATE005 BIG_MUTATION_RATE BSTAG_SOLO500 POP_INIT50 POP1000 MULTIPLE_OFFSPRINGS OFF5',

													 							# 'SETTING13 FITPROP FINITE RATE01 BIG_MUTATION_RATE POP_INIT50 POP1000 TRIALS25',
													 							# 'SETTING13 FITPROP FINITE RATE005 BIG_MUTATION_RATE POP_INIT50 POP1000 TRIALS25',
													 							# 'SETTING13 FITPROP FINITE RATE01 BIG_MUTATION_RATE POP_INIT50 POP1000 TRIALS15',
													 							# 'SETTING13 FITPROP FINITE RATE005 BIG_MUTATION_RATE POP_INIT50 POP1000 TRIALS15',
																			])

																			 
#def build(bld):
#    obj.source = 'StagHuntExp1.cpp'
#    obj.includes = '. ../../'
#    obj.uselib_local = 'sferes2'
#    obj.uselib = ''
#    obj.target = 'StagHuntExp1'
#    obj.uselib_local = 'sferes2'
