#! /usr/bin/env python

import sferes;

def build(bld):
		cxxflags_kdtree = \
				bld.get_env()['CXXFLAGS']\
				+ ['-I.'] \
				+ ['-DLIBSSRCKDTREE_HAVE_BOOST'] \
				+ ['-std=c++0x'] \
				+ ['-m32']

#    lz = bld.new_task_gen('cxx', 'staticlib')
#    lz.source = 'fastlz.cpp'
#    lz.target = 'lz'

#    bld.get_env()['LIB_BZIP2'] = 'bzip2'
#    bld.get_env()['CPPPATH_BZIP2'] = 'bzlib2/include/'
#    bld.get_env()['LIBPATH_BZIP2'] = 'bzlib2/lib/'

#bz = bld.new_task_gen('cxx', 'staticlib')
		#bz.source = 'bzlib2/bzlib.cpp'
		#bz.target = 'bz'

		sferes.create_variants(bld,
													 source='StagHunt.cpp',
													 uselib_local = 'sferes2 fastsim_multi',
#                           uselib = 'EIGEN2 TBB',
													 uselib = 'EIGEN2 SDL FF BOOST_GRAPH TBB',
													 target = 'StagHunt',
#                           json = 'StagHuntExp3.json',
													 variants = [
													 							# 'CONTROL1 ELITIST ONEPLUSONE PREYS2 FIXED_POS EASY_SIMU RANDOM_MUTANT RATE150 BSTAG_SOLO500',

													 							# 'CONTROL1 ELITIST ONEPLUSONE RATE150 BSTAG_SOLO500',
													 							# 'CONTROL1 ELITIST ONEPLUSONE PREYS12 RATE150 BSTAG_SOLO500',

													 							# 'CONTROL1 ELITIST ONEPLUSONE BIG_MUTATION_RATE RATE150 BSTAG_SOLO500',
													 							# 'CONTROL1 ELITIST ONEPLUSONE PREYS12 BIG_MUTATION_RATE RATE150 BSTAG_SOLO500',

													 							# 'CONTROL1 ELITIST ONEPLUSONE POP_INIT100 RATE150 BSTAG_SOLO500',
													 							# 'CONTROL1 ELITIST ONEPLUSONE POP_INIT100 PREYS12 RATE150 BSTAG_SOLO500',

													 							# 'CONTROL1 INFINITE POP_INIT1 PREYS2 FIXED_POS EASY_SIMU RATE150 BSTAG_SOLO500',
													 							# 'CONTROL1 INFINITE POP_INIT100 PREYS2 FIXED_POS EASY_SIMU RATE150 BSTAG_SOLO500',
													 							# 'CONTROL1 INFINITE POP_INIT1 PREYS2 FIXED_POS EASY_SIMU BIG_MUTATION_RATE RATE150 BSTAG_SOLO500',
													 							# 'CONTROL1 INFINITE POP_INIT1 PREYS2 FIXED_POS EASY_SIMU RANDOM_MUTANT RATE150 BSTAG_SOLO500',

													 							# 'SETTING14 FINITE FITPROP POP1000 STD2 RATE01 SSTAG250 POS_CLOSE',

													 							# 'SETTING14 ELITISTINV EVAL_PARENTS POP20 POP_INIT10 STD2 STEP_SIZE SSTAG250 POS_CLOSE',
													 							'SETTING14 ELITISTINV EVAL_PARENTS POP1000 STD2 STEP_SIZE SSTAG250 POS_CLOSE',
													 							# 'SETTING14 ELITISTINV EVAL_PARENTS POP1000 STD2 STEP_SIZE SSTAG50 POS_CLOSE',

													 							# 'SETTING14 ELITISTINV EVAL_PARENTS STD2 SSTAG250 POS_CLOSE',
													 							# 'SETTING14 ELITISTINV EVAL_PARENTS POP1000 STD2 STEP_SIZE SSTAG250 POS_CLOSE',
													 							# 'SETTING14 ELITISTINV EVAL_PARENTS POP1000 STEP_SIZE SSTAG250 POS_CLOSE',
													 							# 'SETTING14 ELITISTINV EVAL_PARENTS POP1000 STD2 SSTAG250 POS_CLOSE',

													 							# 'SETTING14 ELITISTINV EVAL_PARENTS POP20 POP_INIT10 MUT_APP10 EVAL_PERIOD1 STEP_SIZE SSTAG250 POS_CLOSE',
													 							# 'SETTING14 ELITISTINV EVAL_PARENTS POP20 POP_INIT10 MUT_APP10 STEP_SIZE SSTAG250 POS_CLOSE',
													 							# 'SETTING14 ELITISTINV EVAL_PARENTS POP20 POP_INIT10 MUT_APP10 STD2 EVAL_PERIOD1 STEP_SIZE SSTAG250 POS_CLOSE',
													 							# 'SETTING14 ELITISTINV EVAL_PARENTS POP20 POP_INIT10 MUT_APP10 STD2 STEP_SIZE SSTAG250 POS_CLOSE',

													 							# 'SETTING14 FINITE FITPROP EVAL_PARENTS POP1000 STD2 SSTAG250 POS_CLOSE',
													 							# 'SETTING14 INFINITE FITPROP EVAL_PARENTS POP1000 STD2 SSTAG250 POS_CLOSE',
													 							# 'SETTING14 ELITISTINV STD2 SSTAG250 POS_CLOSE',
													 							# 'SETTING14 ELITISTINV STD2 SSTAG250 POS_CLOSE',
																			])

																			 
#def build(bld):
#    obj.source = 'StagHuntExp1.cpp'
#    obj.includes = '. ../../'
#    obj.uselib_local = 'sferes2'
#    obj.uselib = ''
#    obj.target = 'StagHuntExp1'
#    obj.uselib_local = 'sferes2'
