#! /usr/bin/env python

import sferes;

def build(bld):
		cxxflags_kdtree = \
				bld.get_env()['CXXFLAGS']\
				+ ['-I.'] \
				+ ['-DLIBSSRCKDTREE_HAVE_BOOST'] \
				+ ['-std=c++0x'] \
				+ ['-m32']

#    lz = bld.new_task_gen('cxx', 'staticlib')
#    lz.source = 'fastlz.cpp'
#    lz.target = 'lz'

#    bld.get_env()['LIB_BZIP2'] = 'bzip2'
#    bld.get_env()['CPPPATH_BZIP2'] = 'bzlib2/include/'
#    bld.get_env()['LIBPATH_BZIP2'] = 'bzlib2/lib/'

#bz = bld.new_task_gen('cxx', 'staticlib')
		#bz.source = 'bzlib2/bzlib.cpp'
		#bz.target = 'bz'

		sferes.create_variants(bld,
													 source='StagHunt.cpp',
													 uselib_local = 'sferes2 fastsim_multi',
#                           uselib = 'EIGEN2 TBB',
													 uselib = 'EIGEN2 SDL FF BOOST_GRAPH TBB',
													 target = 'StagHunt',
#                           json = 'StagHuntExp3.json',
													 variants = [
													 							# 'SETTING13 PREYS2',
													 							# 'SETTING13 PREYS10',
													 							# 'SETTING13',

													 							# 'CONTROL1 BSTAG1000 BSTAG_SOLO1000 PREYS2',
													 							# 'CONTROL1 BSTAG1000 BSTAG_SOLO1000 PREYS10',
													 							# 'CONTROL1 BSTAG1000 BSTAG_SOLO1000',

													 							'SETTING13 RATE01 INVASION01',
													 							'SETTING13 RATE01 INVASION05',
													 							'SETTING13 RATE01 INVASION001',
													 							'SETTING13 RATE01 INVASION005',
													 							'SETTING13 RATE03 INVASION01',
													 							'SETTING13 RATE03 INVASION05',
													 							'SETTING13 RATE05 INVASION01',
													 							'SETTING13 RATE05 INVASION05',
													 							'SETTING13 RATE001 INVASION01',
													 							'SETTING13 RATE001 INVASION05',
													 							'SETTING13 RATE003 INVASION01',
													 							'SETTING13 RATE003 INVASION05',
													 							'SETTING13 RATE005 INVASION01',
													 							'SETTING13 RATE005 INVASION05',

													 							# 'SETTING15 PREYS2',
													 							# 'SETTING15 PREYS10',
													 							# 'SETTING15',

													 							# 'CONTROL1 PREYS2',
													 							# 'CONTROL1 PREYS10',
													 							# 'CONTROL1',
																			])

																			 
#def build(bld):
#    obj.source = 'StagHuntExp1.cpp'
#    obj.includes = '. ../../'
#    obj.uselib_local = 'sferes2'
#    obj.uselib = ''
#    obj.target = 'StagHuntExp1'
#    obj.uselib_local = 'sferes2'
